spring:
  application:
    name: backend-item
  rabbitmq:
      addresses: 127.0.0.1
      username: guest
      password: guest
      port: 5672
      virtual-host: /

server:
  port: 9011

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
      prefer-ip-address: true

tx-lcn:
  client:
    manager-address: 127.0.0.1:8070

FTP_HOST: 192.168.70.144
FTP_PORT: 21
FTP_USERNAME: ftpuser
FTP_PASSWORD: ftpuser
FTP_BASEPATH: /home/ftpuser/


